#SQL
#连接地址，用户名，密码
sql:
  url: 'jdbc:mysql://molecular-assembler/daily_sign?useSSL=false'
  username: 'root'
  password: ''

#Server
#服务器组，玩家同一天可以在不同的服务器组中各获得一次签到奖励
serverGroup: 'A'

#Resign
#当天数小于等于该值时所需的数量
#从小到大顺序 打乱将不会正常工作
resignRequirements:
    3: 2
    5: 3
    7: 4
    15: 7

#补签卡物品
resignItem:
  ==: org.bukkit.inventory.ItemStack
  type: STONE

#奖励配置
rewardSetting:
  ==: DailySign.RewardSetting
  #日常签到奖励
  generic:
    ==: DailySign.RewardWithBonus
    #普通奖励
    reward:
      #以奖励池形式随机发放奖励
      ==: DailySign.RewardPool
      rewards:
        #权重50
        50:
          ==: DailySign.Reward
          #奖励一组石头
          items:
            -
              ==: org.bukkit.inventory.ItemStack
              type: STONE
              amount: 64
    #特殊权限用户额外奖励
    bonus:
      #特殊权限
      dailysign.vip1:
        #固定奖励
        ==: DailySign.Reward
        #执行后台命令
        commands:
          - say Hello World
      dailysign.vip2:
        #以奖励池形式随机发放奖励
        ==: DailySign.RewardPool
        rewards:
          #权重50
          50:
            ==: DailySign.Reward
            #奖励一组石头
            items:
              -
                ==: org.bukkit.inventory.ItemStack
                type: STONE
                amount: 64
  #连续签到奖励
  streak:
    #连续签到天数
    3:
      ==: DailySign.RewardWithBonus
      reward:
        ==: DailySign.Reward
        #奖励一组原石
        items:
          -
            ==: org.bukkit.inventory.ItemStack
            type: COBBLESTONE
            amount: 64
      #额外奖励不配置
      bonus: {}


messages:
    #Generic
    Command_Player_Only: '该命令只能由玩家执行.'
    Internal_Error: '内部错误,请联系管理员.'
    Not_Enough_Requirements: '所需物品不足.'
    #Get
    Already_Claimed: '您已领取过当日签到礼包.'
    #Rank
    Invalid_Type: '无效的类型'
    Rank_List_Header: '-----签到排行榜 第{0}页-----'
    Rank_List_Entry: '{0}: 总签到{1} 连续签到{2} 历史最高{3}'
    #Info
    Info_Format: '玩家: {0}|总签到: {1}|连续签到: {2}|历史最高: {3}'
    #Sign
    Sign_Success: '签到成功!'
    #GUI
    Unresignable: '因时间过久,已无法补签.'
    Gui_Inventory_Name: '每日签到'
    Gui_Get_Reward: '领取今日签到奖励'
    Gui_Sign: '点击签到'
    Gui_Prev_Month: '上一页'
    Gui_Next_Month: '下一页'
