name: DailySign
main: love.sola.spigot.dailysign.DailySign
version: 1.0
commands:
   qiandao:
      description: Sola.
      usage: |
        /<command>  --签到
        /<command> info  --签到信息
        /<command> top  --签到排行
